import { TransactionType } from "@/types/api-types";

export const transactionSource: TransactionType[] = [
  {
    id: "1",
    name: "Transfer",
    slug: "8201",
    price: "0.2 ETH",
    from: "chizaalabs",
    to: "cryptofarmer",
    timeListed: "12 days ago",
  },
  {
    id: "2",
    name: "Transfer",
    slug: "4303",
    price: "0.2 ETH",
    from: "web3clubs",
    to: "chizaalabs",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "Transfer",
    slug: "4301",
    price: "0.2 ETH",
    from: "chizaalabs",
    to: "web3clubs",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "Transfer",
    slug: "2301",
    price: "0.2 ETH",
    from: "chizaalabs",
    to: "cryptofarmer",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "Transfer",
    slug: "8201",
    price: "0.2 ETH",
    from: "vasp",
    to: "cryptofarmer",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "Transfer",
    slug: "8201",
    price: "0.2 ETH",
    from: "jyuko",
    to: "cryptofarmer",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "Transfer",
    slug: "8201",
    price: "0.2 ETH",
    from: "koolnina",
    to: "cryptofarmer",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "Transfer",
    slug: "8201",
    price: "0.2 ETH",
    from: "happyfriends",
    to: "cryptofarmer",
    timeListed: "12 days ago",
  },
];
